POST http://localhost:8081
Content-Type: application/x-www-form-urlencoded

url=https://music.163.com/#/song?id=35847388

###

POST http://localhost:8081
Content-Type: application/x-www-form-urlencoded

url=https://music.163.com/#/discover/playlist

###

GET http://localhost:8080/demo/queryAll

###

POST http://localhost:8080/demo/insert
Content-Type: application/x-www-form-urlencoded

name=test3

###
